version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install docs/requirements.txt
      - pip install sphinx furo pygments sphinx_copybutton sphinx-autobuild tgcrypto
      - cd compiler/docs && python compiler.py

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
